{% set name = "webruntime" %}
{% set version = "0.5.7" %}
{% set sha256 = "82ec9392ef46291886d03160bcb73270162e8842b378b20124d63d1ff1796acc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - dialite

test:
  imports:
    - webruntime

about:
  home: http://webruntime.readthedocs.io
  doc_url: http://webruntime.readthedocs.io
  dev_url: https://github.com/flexxui/webruntime
  summary: Launch web apps making them look like desktop apps.
  license: BSD 2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - almarklein
