travis:
  secure:
    BINSTAR_TOKEN: koduTuqY6sp2Ov99lc/xGHcPZ83caDGY6ZT1LCzcrj7zOOm+g3j7CnhhPzwntheaLWB0h9K0XPOgcnJzH1FmgmACkwyZLUm/+dGv4HhdfTOTJfA3G2YiqNEIPGvs67BZpIlyQOire+6+7q+L/nbKbnjGEgWUbRzBCQ/gOW5nYxQAlLfLx7SLuM1Z2ekJ1whWX9l73jqrWU0IdOlu+uxrmloU41GnE/si+PKN1Pdi/H7LiFeF9OfxkjNzN0rHLQuR/zhutfvlPR1TFGfr/8jWD56e+ALgo2CIjF0S+0WyfHEj7P5w1h/druog29R4tkKB2NCXdEiLHlr4VjzlZi15Xlb0HuqSEm1vUY5wozTmhwr6CSR4ItoYsE7T+TFuY4NH4wzNFZMriMUIWEl7IueG0kDeQjseqBlXSI1OGNmlF2hFsWGI74FghEtyLZeTGOFCLv6t638gS9UcyocAl9sAbO8h4j5eDOUGh3lkdBdZp096JzviTI5Yax605nukCzJlTTrtSg+Z68sAAfMIIffiN9F6J6M/wLv2ix2A/HeaiXlf2ujcpM9jCNzYEVVwspAam570tiStUww0HWcDRVtAE3DRv2iIwop1DgiF/gitPmKcn0OdiGwNDFsoLbixRZJOBIDMRi7vypymcPwdDZ0V7uEYclHOjbJJ+tVf4PEKHMA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
